#!/bin/bash

#	Init of all needed varible

DEBUG=false
CURL_ARGS="-s" # default "-s"

TOKEN="$(cat bot_token.txt)"
URL="https://api.telegram.org/bot${TOKEN}"
LMidFILE="last_message_id.txt"
DEST=/mnt/hard_drive1/zopiBot_trash

if ! $DEBUG ; then
	TEMP_DIR=/run/user/1000/telegram_bot
	RAM_JSON=$TEMP_DIR/answer.json
	CMD_FLAG=$TEMP_DIR/cmd_flag.txt
	CMD_ARGS=$TEMP_DIR/cmd_args.txt
	SIG_to_DIE=$TEMP_DIR/status
	
	#TEMP_DIR=$(mktemp -dt "tBot.XXXXXXXX" --tmpdir=/run/user/$(id -u))
	#RAM_JSON=$(mktemp -t "json.XXXXXXXX" --tmpdir=$TEMP_DIR)
	#CMD_FLAG=$(mktemp -t "cmd_flag.XXXXXXXX" --tmpdir=$TEMP_DIR)
	#CMD_ARGS=$(mktemp -t "cmd_args.XXXXXXXX" --tmpdir=$TEMP_DIR)
else
	TEMP_DIR=$(mktemp -dt "tBot.XXXXXXXX" --tmpdir=/run/user/$(id -u))
	#TEMP_DIR="${HOME}/git/bash/telegram_bot/tBot_d"
	RAM_JSON="${TEMP_DIR}/json_d.txt"
	#RAM_JSON=/run/user/1000/tBot.ldfxYEiV/json.IFefd77O
	CMD_FLAG="${TEMP_DIR}/cmd_flag_d.txt"
	CMD_ARGS="${TEMP_DIR}/cmd_args_d.txt"
fi

#if [[ ! -e $RAM_JSON ]]; then
	mkdir -p $TEMP_DIR
	touch $RAM_JSON
	touch $CMD_FLAG
	touch $CMD_ARGS
	touch $SIG_to_DIE
#fi

