#!/bin/bash

#	Init of all needed varible

DEBUG=false
DEBUG_OUTPUT="false"
TOR_EN="false"
CURL_ARGS="-s --max-time 30 --output $SFB_JSON" # default "-s"
[[ "$TOR_EN" == "true" ]] && CURL_ARGS+=" --proxy socks4://127.0.0.1:9050"
TOKEN="$(cat ${CORE_DIR}/bot_token.txt)"
URL="https://api.telegram.org/bot${TOKEN}"
LMidFILE="${CORE_DIR}/last_message_id"
LMdateFILE="${CORE_DIR}/last_message_date"
DEST="/mnt/hard_drive1/zopiBot_trash"
MAIN_MENU='[
			["показать все функции","показать помощь"],
			["включить котёл","выключить котёл"],
			["температура дома","ЧАВО"]
		   ]'

HELP_en="Hello, this is bot for testing and fun sheet.
Made by zulljon.
Avialable commands:
/exec - execute command in /bin/bash, and get its result
/espeak - get voice message of text (use espeak from linux repo)
/speakru - get voice message of text on russian (use festvox-ru from linux repo)
/sayru - say in speakers on russian"
HELP_ru="Привет, этот бот для тестирования всякой всячины и развлечений.
Создатель и повелитель - zulljon.
Доступные комманды:
/exec - запуск команд /bin/bash, и получить результат выполнения
/espeak - голосовое сообщение текста (использует espeak из linux репозитория)
/speakru - голосовое сообщение русского текста (use festvox-ru from linux repo)
/sayru - проиграть голосовое сообщение в динамиках"



if ! $DEBUG ; then
#	TEMP_DIR=/run/user/1000/telegram_bot
	TEMP_DIR="/tmp/telegram_bot"
	RAM_JSON="${TEMP_DIR}/answer.json"
	SFB_JSON="${TEMP_DIR}/server_feedback.json"
	CMD_FLAG="${TEMP_DIR}/cmd_flag.txt"
	CMD_ARGS="${TEMP_DIR}/cmd_args.txt"
	SIG_to_DIE="${TEMP_DIR}/status"

	#TEMP_DIR=$(mktemp -dt "tBot.XXXXXXXX" --tmpdir=/run/user/$(id -u))
	#RAM_JSON=$(mktemp -t "json.XXXXXXXX" --tmpdir=$TEMP_DIR)
	#CMD_FLAG=$(mktemp -t "cmd_flag.XXXXXXXX" --tmpdir=$TEMP_DIR)
	#CMD_ARGS=$(mktemp -t "cmd_args.XXXXXXXX" --tmpdir=$TEMP_DIR)
else
	TEMP_DIR=$(mktemp -dt "tBot.XXXXXXXX" --tmpdir="/run/user/$(id -u)")
	#TEMP_DIR="${HOME}/git/bash/telegram_bot/tBot_d"
	RAM_JSON="${TEMP_DIR}/json_d.txt"
	#RAM_JSON=/run/user/1000/tBot.ldfxYEiV/json.IFefd77O
	CMD_FLAG="${TEMP_DIR}/cmd_flag_d.txt"
	CMD_ARGS="${TEMP_DIR}/cmd_args_d.txt"
fi

#if [[ ! -e $RAM_JSON ]]; then
	mkdir -p "$TEMP_DIR"
	touch "$RAM_JSON"
	touch "$CMD_FLAG"
	touch "$CMD_ARGS"
	touch "$SFB_JSON"
	echo "0" > $SIG_to_DIE
#fi
